export const SIGN_UP = {
  TITLE: 'הצטרפו לקהילה, צרו חשבון',
  FIRST_NAME_TITLE: 'שם פרטי',
  FIRST_NAME_PLACEHOLDER: 'הזינו שם פרטי',
  LAST_NAME_TITLE: 'שם משפחה',
  LAST_NAME_PLACEHOLDER: 'הזינו שם משפחה',
  USERNAME_TITLE: 'אימייל',
  USERNAME_PLACEHOLDER: 'הזינו אימייל',
  PASSWORD_TITLE: 'סיסמא',
  PASSWORD_PLACEHOLDER: 'הזינו סיסמא',
  BUTTON: 'שליחה',
  INPUT_ERROR_TEXT: 'הינו שדה חובה',
  ALTER_TITLE: 'או היכנסו עם',
  ERR_LABEL: 'אירעה שגיאה',
};
